### ISSUE TITLE
Неправильно общение между активити и фрагментом

### ISSUE THREAD

**Issue by neikila** [Qubiq1337/DZ1#1]
https://github.com/Qubiq1337/DZ1/blob/7886145056dbec2f12d89e35d2121b1e4a683aef/app/src/main/java/com/example/dz1/Fragment1.java#L123

Я указывал в посте, что нельзя расскрывать во фрагменте информацию о структуре и поведении активитии.
Код создания и замены фрагментов должен находиться в активити. См. пост на портале.

**Comment by Qubiq1337** [comment]
Исправил.
